name: seismod-env
channels:
  - conda-forge
  - msys2
dependencies:
  - mkl=2020.2
  - m2w64-toolchain=5.3.0
  - python>=3.7.2,<=3.8.5
  - libpython=2.0
  - setuptools=49.6.0
  - pip=20.2.3
  - numpy=1.19.1
  - scipy=1.5.0
  - matplotlib=3.3.1
  - theano=1.0.5
  - pymc3=3.9.3
  - python-dateutil=2.8.1
  - sphinx=3.2.1
  - recommonmark=0.6.0
  - pip:
    - methodtools
